name: "Synchronise rota with PagerDuty"

on:
  schedule:
    # synchronise PagerDuty every hour (8pm-6pm) during the working week
    - cron:  '0 8-18 * * 1-5'
  workflow_dispatch: {}

jobs:
  sync-pagerduty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Synchronise PagerDuty
        run: bundle exec rake sync_pagerduty[true]
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY : ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          PAGER_DUTY_API_KEY: ${{ secrets.PAGER_DUTY_API_KEY }}
          ROTA_SHEET_URL: ${{ secrets.ROTA_SHEET_URL }}
          ROTA_TAB_NAME: ${{ secrets.ROTA_TAB_NAME }}

      - name: Notify failure
        uses: slackapi/slack-github-action@v1
        if: ${{ failure() }}
        with:
          payload: |
            {
              "text": "The <https://github.com/alphagov/govuk-rota-generator/blob/main/.github/workflows/sync_pagerduty.yml|PagerDuty sync script> failed.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The <https://github.com/alphagov/govuk-rota-generator/blob/main/.github/workflows/sync_pagerduty.yml|PagerDuty sync script> failed."
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Check the build logs for details"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "action_id": "button-view-workflow"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
